### ISSUE TITLE
Feature Request: Exclude namespaces 

### ISSUE THREAD

**Issue by abhisheks-infracloud** [titansoft-pte-ltd/imagepullsecret-patcher#2]
Hi, Thanks for the wonderful tool. I was wondering if we can add feature to exclude some of the namespaces which don't require imagePull secret like Kube-System, Default etc.

If you have this feature already in your road-map that's great. If not, may be you can consider adding this feature. 
Love to hear your feedback.

**Comment by billjh** [comment]
Hi @abhisheks-infracloud, thanks for the suggestion! 

I have two ideas in mind to support namespace exclusions
1. a comma-separated list provided to the application, eg. CONFIG_EXCLUDENAMESPACES="kube-system,default"
2. an annotation on the namespaces themselves, eg. k8s.titansoft.com/imagepullsecret-patcher-exclude: "true"

I plan to implement both in the next release v0.10, and let me know what you think :D

**Comment by discordier** [comment]
Even if I am not addressed, I prefer the annotation solution, as it won't make reconfiguring of the pod necessary.

**Comment by abhisheks-infracloud** [comment]
Hi @billjh, Both the options looks good to me. 
@discordier For the first option, we can create the helm chart and pass the values through values.yaml file so that we don't need to change pod spec configuration.

**Comment by discordier** [comment]
@abhisheks-infracloud I use gitlab for registry and deployment (which automatically creates a namespace per project) so redeploying via helm over and over again is not possible for me.
Therefore the annotation for excluded namespaces is perfect for me as everything that is created from gitlab side should be patched and all namespaces I create "by hand" (let it be helm, kubectl or anything else) can then be marked as "ignored" without redeploying any charts.

**Comment by abhisheks-infracloud** [comment]
@discordier  By using helm chart I meant to create the Helm chart for "imagepullsecret-patcher" and define an environment variable like EXCLUDE_NAMESPACES= and pass the list of namespaces to be excluded. In this we don't need to patch the namespaces that are already created or dynamically created.

**Comment by billjh** [comment]
This feature is released in v0.10
https://github.com/titansoft-pte-ltd/imagepullsecret-patcher/releases/tag/v0.10
