### ISSUE TITLE
v0.9 is not available on quay.io

### ISSUE THREAD

**Issue by discordier** [titansoft-pte-ltd/imagepullsecret-patcher#3]
First off, thanks for the solution. I had the same idea and thankfully before implementing it myself found your repository.

I don't know if you realized it but:
1. the travis build of tag 0.9 failed
2. the image is not pushed to quay.io causing deployment to fail.

Could you please push the image to quay.io?

**Comment by billjh** [comment]
I didn't realize the pipeline for v0.9 failed. Thanks for point out!

It seemed to be some issue with travis go environment setup from the log. I already restart the job, and tag v0.9 is now available
https://quay.io/repository/titansoft/imagepullsecret-patcher?tab=tags

To prevent this from happening again, I created a new issue #4.
