### ISSUE TITLE
Add CI pipeline notification for Travis

### ISSUE THREAD

**Issue by billjh** [titansoft-pte-ltd/imagepullsecret-patcher#4]
To prevent issues like #3 happen again

**Comment by discordier** [comment]
Don't know how you registratered yourself at travis but I also receive email notifications from travis for failed builds. This might be an intermediate solution until you have your pipeline in place.

**Comment by billjh** [comment]
Hi @discordier, I guess I didn't receive the email due to some organization setting on Github. Working with my admin on that now. Thanks for the suggestion!

**Comment by billjh** [comment]
Travis CI and Github notification has been configured
